import streamlit as st
import pandas as pd
from main import master_df, generate_monte_carlo, generate_expense_pie_chart, df

chosen_archetype = st.session_state.arch

st.header("About your Archetype")
st.write(f'See below for more info on {chosen_archetype}\'s spending habits.')

chosen_df = master_df[master_df['customer_id'] == chosen_archetype]

st.markdown(f":money_with_wings: **Average Monthly Expense Total:** ${chosen_df.iloc[0, 3]}")
st.markdown(f" **Average # of Expenses Monthly:** {chosen_df.iloc[0, 4]}")

st.subheader("Expense Pie Chart :chart_with_upwards_trend:")
pie_fig = generate_expense_pie_chart(chosen_archetype)
st.pyplot(pie_fig)

st.subheader("Most Common Expenses :clipboard:")
st.write("Note: Expenses are shown as they appear on credit card transaction history, which may not completely reflect the title of the purchase.")
cmn_exp = pd.DataFrame.from_dict(chosen_df.iloc[0,7])[1:]
st.write(cmn_exp.iloc[0])

st.subheader("Expected Future Expenses :chart_with_downwards_trend:")
st.write("The graph below, generated by a Monte Carlo simulation, runs thousands of scenarios dependent on variable expenses to determine how likely a given case is. The areas on the graph with the highest peaks are those scenarios most common (and therefore most likely to occur).")

before_fig, before_ax, finals, months = generate_monte_carlo(chosen_archetype)
st.pyplot(before_fig)
before_fig_copy = before_fig
finals_df = pd.DataFrame(finals)
finals_df.columns = ['price']
before_low_10 = finals_df['price'].quantile(0.10).round(2)
before_top_10 = finals_df['price'].quantile(0.90).round(2)
st.markdown(f":negative_squared_cross_mark: In the worst 10% of scenarios, you spend **${before_top_10} over {months} months.**")
st.markdown(f":white_check_mark: But, in the best 10% of cases, you only spend **${before_low_10} in {months} months.**")
st.markdown("Using this data can be advantageous because it allows you to prepare a safety net. If you know the upper limit of your expenses, you don't need to worry too much about not having enough (aside from unpredictable emergency costs, of course). :goal_net:")

st.write("And this information is great and all, but wouldn't it be great if there was a way we could **lower this spending...?** :thinking:")
if st.button("Continue"):
    st.session_state.before_fig = before_fig
    st.session_state.before_fig_copy = before_fig_copy
    st.session_state.before_ax = before_ax
    st.session_state.before_finals = finals
    st.session_state.before_finals_df = finals_df
    st.session_state.before_low_10 = before_low_10
    st.session_state.before_top_10 = before_top_10
    st.switch_page("pages/tips.py")